repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: end-of-file-fixer
      files: ^(src/|tests/)
    - id: trailing-whitespace
      files: ^(src/|tests/)
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.2  # Use the latest version
  hooks:
    # Run the linter.
    - id: ruff-check
      files: ^(src/|tests/)
    # Run the formatter.
    - id: ruff-format
      files: ^(src/|tests/)
